// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCincPk3g136JfIjC2ajBfnVwyo9_TrZRw',
    appId: '1:34498692880:web:e1ea68c9f8915ae65e4795',
    messagingSenderId: '34498692880',
    projectId: 'campusphere-76f06',
    authDomain: 'campusphere-76f06.firebaseapp.com',
    storageBucket: 'campusphere-76f06.firebasestorage.app',
    measurementId: 'G-0MHCS6KS8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHf3em2D3XoTtXxFDZVQv_j2PD4qsX1E',
    appId: '1:34498692880:android:14dd514809eaa0c25e4795',
    messagingSenderId: '34498692880',
    projectId: 'campusphere-76f06',
    storageBucket: 'campusphere-76f06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnPe4MmIJPDOK8fYTRm1TV-28eb8CCb_I',
    appId: '1:34498692880:ios:d7f4e8e40d6b2d6e5e4795',
    messagingSenderId: '34498692880',
    projectId: 'campusphere-76f06',
    storageBucket: 'campusphere-76f06.firebasestorage.app',
    iosBundleId: 'com.example.campusphereFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnPe4MmIJPDOK8fYTRm1TV-28eb8CCb_I',
    appId: '1:34498692880:ios:d7f4e8e40d6b2d6e5e4795',
    messagingSenderId: '34498692880',
    projectId: 'campusphere-76f06',
    storageBucket: 'campusphere-76f06.firebasestorage.app',
    iosBundleId: 'com.example.campusphereFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCincPk3g136JfIjC2ajBfnVwyo9_TrZRw',
    appId: '1:34498692880:web:09d002973b9c27435e4795',
    messagingSenderId: '34498692880',
    projectId: 'campusphere-76f06',
    authDomain: 'campusphere-76f06.firebaseapp.com',
    storageBucket: 'campusphere-76f06.firebasestorage.app',
    measurementId: 'G-QJ14Q8MK65',
  );
}
