spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: campusphere-backend
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: ${JWT_SECRET}

